spring:
  application:
    name: pal-tracker
  boot:
    admin:
      url: https://pal-tracker-sandbox.apps.pikes.pal.pivotal.io
      auto-registration: true
      auto-deregistration: true
      register-once: true
      context-path: /admin

security:
  basic:
    enabled: false

custom:
  metric:
    timeEntries-count: "timeEntries.count"
    timeEntries-created: "timeEntries.created"
    timeEntries-deleted: "timeEntries.deleted"
    timeEntries-read: "timeEntries.read"
    timeEntries-listed: "timeEntries.listed"
    timeEntries-updated: "timeEntries.updated"